# Generated by Django 4.0.5 on 2022-06-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do evento')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img7', models.ImageField(blank=True, null=True, upload_to='img')),
                ('img8', models.ImageField(blank=True, null=True, upload_to='img')),
                ('type', models.CharField(max_length=120, verbose_name='Tipo do evento')),
                ('name', models.CharField(max_length=120, verbose_name='Nome do evento')),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
