# Generated by Django 4.0.5 on 2022-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('id_number', models.IntegerField(verbose_name='ID')),
                ('departamento', models.CharField(max_length=120, verbose_name='Departamento')),
                ('email', models.EmailField(max_length=120)),
                ('desc', models.TextField(max_length=240, verbose_name='Descrição da oportunidade')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
