# Generated by Django 4.0.5 on 2022-06-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '004_sla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='recursos',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=120),
        ),
    ]
