# Generated by Django 4.0.5 on 2022-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_oportunidade_recursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('Em espera', 'Em espera'), ('Em progresso', 'Em progresso'), ('Finalizado', 'Finalizado')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
