# Generated by Django 4.0.5 on 2022-06-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_event_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_approved',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
