# Generated by Django 4.0.5 on 2022-06-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_event_is_approved_remove_event_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunidade',
            name='state',
            field=models.CharField(choices=[('Em espera', 'Em espera'), ('Em progresso', 'Em progresso'), ('Finalizado', 'Finalizado')], default='Em espera', max_length=120),
        ),
    ]
