# Generated by Django 4.0.5 on 2022-06-26 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_mynote_user_delete_profilenotes'),
    ]

    operations = [
    migrations.AlterField(
            model_name='mynote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
